### PR TITLE
Potential fix for "game already claimed"

### PR DESCRIPTION
**Pull request by BahMike**
This removes the error but I'm not certain yet if it actually purchases the games as I already have them.

### CODE REVIEW

**Comment by YaBoiAce** [comment]
I'll try it right now and let you know.

**Comment by YaBoiAce** [comment]
I went ahead and tried it out; it does not purchase the games/add it to the person's library.
Output:
`Successfully claimed Close to the Sun (CHECKOUT)`
`Successfully claimed Sherlock Holmes Crimes and Punishments (CHECKOUT)`
`Successfully claimed Lego Batman Trilogy (CHECKOUT)`
note: I already had Sherlock Holmes Crimes and Punishments.

**Comment by MusTangLee** [comment]
This doesn't seems to work.
I would guess quickPurchase means purchasing stuff that does not induce a checkout page/request or it would act like "add to cart" action.

This is the implementation of purchase from node-epicgames-client which is already used in the script:

```
  async purchase(offer, quantity) {

    const quickPurchaseStatus = await this.quickPurchase(offer, quantity);

    switch (quickPurchaseStatus) {

      case 'SUCCESS':
        return true;

      case 'CHECKOUT': {
        const purchase = await this.newPurchase(offer);
        const order = await this.purchaseOrderPreview(purchase, offer);
        if (!order) return false;
        return this.purchaseOrderConfirm(purchase, order);
      }

      default:
        throw new Error(`Unknown quick purchase status: ${quickPurchaseStatus}`);

    }

  }
```

It would seem, purchase also uses quickPurchase but will handle the CHECKOUT status aswell!
@Revadike seems like you tried some of the purchase combinations, saw some of your posts on the node-epicgames-client discord regarding this behavior.

**Comment by Revadike** [comment]
`quickPurchase()` uses `purchase()` anyway, so that likely doesn't solve anything.
I haven't been able to reproduce this issue yet.

**Pull request closed without merging**
