### PR TITLE
Update gimme_free_epic_shit.js

### PR DESCRIPTION
**Pull request by lupohan44**
Allow program to run infinity
Support multi accounts

### CODE REVIEW

**Comment by Revadike** [comment]
Thanks for your PR!
I've reviewed it and here are my notes:

 * Please use the styling as defined in the ESLint config. I'd recommend using an ESLint plugin for your code editor, so you can autofix it.
 * Why do you need to require `async`?
 * Please include your config update (#11 ) in this PR.
 * I think, because `ClientLoginAdapter` can be used multiple times now, it should be required once on top.
 * Shouldn't `rememberLastSession` be set per account?
 * The reason why I used `process.exit()` was because it wouldn't end otherwise. Have you tested this? It may have changed with the latest version of `epicgames-client`. However, if not, I think you should keep this, in case `loop` is set to `false`.

Other than that, it looks good.

**Comment by Revadike** [comment]
Also, I think you should put delay at the end of the loop and only if it will loop forever, because you may want to set delay to 24 hours, then imagine you run the script and you have to wait 24 hours before something happens.

**Comment by lupohan44** [comment]
1.I use notepad++, so I'm not sure what kind of format we need
2.It can be removed
3.Ok
4.Ok
5.I think rememberLastSession should be a global setting?
6.I never tested it, I will add it back

**Comment by lupohan44** [comment]
7.Ok

**Comment by lupohan44** [comment]
{
	"accounts": [{ "email": "YOUR_EMAIL1_HERE","password": "YOUR_PASSWORD1_HERE"},{"email": "YOUR_EMAIL2_HERE","password": "YOUR_PASSWORD2_HERE" }],
	"delay": 3600,
	"loop": true,
    "rememberLastSession": true
}

Is this format correct?

**Comment by Revadike** [comment]
> 1.I use notepad++, so I'm not sure what kind of format we need

https://github.com/deadem/notepad-pp-linter

> 2.It can be removed

I'd remove it then

> 5.I think rememberLastSession should be a global setting?

Why's that?

**Comment by lupohan44** [comment]
> > 1.I use notepad++, so I'm not sure what kind of format we need
> 
> https://github.com/deadem/notepad-pp-linter
> 
I'm not sure how to use it
> > 2.It can be removed
> 
> I'd remove it then
> 
> > 5.I think rememberLastSession should be a global setting?
> 
> Why's that?
I think nobody use different rememberLastSession settings on different accounts

**Comment by lupohan44** [comment]
33:21  error  Blocks are nested too deeply (5). Maximum allowed is 4  max-depth
  59:21  error  Blocks are nested too deeply (5). Maximum allowed is 4  max-depth
  62:25  error  Blocks are nested too deeply (6). Maximum allowed is 4  max-depth


I think I can't fix these

**Comment by Revadike** [comment]
> 33:21 error Blocks are nested too deeply (5). Maximum allowed is 4 max-depth
> 59:21 error Blocks are nested too deeply (5). Maximum allowed is 4 max-depth
> 62:25 error Blocks are nested too deeply (6). Maximum allowed is 4 max-depth
> 
> I think I can't fix these

That's fine. As long as the rest is ok.

**Comment by lupohan44** [comment]
Duplicate of #15

**Pull request closed without merging**
