### PR TITLE
support 2fa

### PR DESCRIPTION
**Pull request by lingsamuel**
Already tested in [my GitHub Action](https://github.com/lingsamuel/EpicGamesGiveawaysAutoClaimer_Instance/blob/master/.github/workflows/Get_Epic_Game.yml) ([result](https://github.com/lingsamuel/EpicGamesGiveawaysAutoClaimer_Instance/runs/659021976)).

### CODE REVIEW

**Comment by lupohan44** [comment]
Duplicate of #18

**Comment by lingsamuel** [comment]
> Duplicate of #18

One functionality, one PR.
And your PR said:
> I can't bypass this

**Comment by lupohan44** [comment]
> > Duplicate of #18
> 
> One functionality, one PR.
> And your PR said:
> 
> > I can't bypass this

that is "check update"

**Comment by Revadike** [comment]
Have you checked out this function? https://epicgames-client.kysune.me/Client.html#enabletwofactor-type-twofactorcode

It would be nice if you can make this work.

**Comment by lupohan44** [comment]
> Have you checked out this function? https://epicgames-client.kysune.me/Client.html#enabletwofactor-type-twofactorcode
> 
> It would be nice if you can integrate this too.

that function is to enable account's 2fa

**Comment by Revadike** [comment]
> > Have you checked out this function? https://epicgames-client.kysune.me/Client.html#enabletwofactor-type-twofactorcode
> > It would be nice if you can integrate this too.
> 
> that function is to enable account's 2fa
> i don't think we should enable user's 2fa

Maybe temporarily enable it just for claiming a free game, if the user hasn't enabled it before.

**Comment by lupohan44** [comment]
> > > Have you checked out this function? https://epicgames-client.kysune.me/Client.html#enabletwofactor-type-twofactorcode
> > > It would be nice if you can integrate this too.
> > 
> > 
> > that function is to enable account's 2fa
> > i don't think we should enable user's 2fa
> 
> Maybe temporarily enable it just for claiming a free game, if the user hasn't enabled it before.

but if you enable it and before disable it, something went wrong and the program just crashed, user can't login to his account anymore

**Comment by SzymonLisowiec** [comment]
@lupohan44 can you share your code of enabling/disabling tfa?

**Comment by lupohan44** [comment]
> @lupohan44 can you share your code of enabling/disabling tfa?

i didn't implement that
https://github.com/Revadike/epicgames-freebies-claimer/pull/21/commits/9aa8d69fd562bce80dd8c7e47d43584f559f1136
you can simply add 2fa enable before line 44(if not set secret and code) and disable before file ended

**Pull request merged**
