### PR TITLE
optional pushbullet notifications

### PR DESCRIPTION
**Pull request by ffuubarbuzz**

### CODE REVIEW

**Comment by Revadike** [comment]
Awesome addition, thanks!

**Comment by ffuubarbuzz** [comment]
@Revadike Happy to help :) Is docker container published automatically or it needs to be done manually? If latter, could you please do it?

**Comment by Revadike** [comment]
@jackblk

**Comment by jackblk** [comment]
@ffuubarbuzz I maintain the docker image so I will push an update tomorrow.

**Comment by jackblk** [comment]
@ffuubarbuzz @Revadike I pushed the new version to Dockerhub & GithubPackage. Enjoy :).

**Pull request merged**
